application: aarons1514
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /static/images
  static_dir: static/images

- url: /.*
  script: crawler.py